// <auto-generated />
using System;
using Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivePeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActivePeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlertCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cause")
                        .HasColumnType("int");

                    b.Property<string>("Description_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndActivePeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndActivePeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModification")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
